import Head from 'next/head'
import Navbar from './../components/Navbar/Navbar.jsx'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <div className='text-t-orange bg-t-blue '>Test</div> */}
    <Navbar/>
    </>
  )
}
